image: haskell:8.10.7

variables:
  STACK_ROOT: "${CI_PROJECT_DIR}/.stack"

cache:
  paths:
    - .stack
    - .stack-work

before_script:
  - stack config set system-ghc --global true

build:
  stage: build
  script:
    - stack --no-terminal build

test:
  script:
    - stack --no-terminal test --coverage --haddock --no-haddock-deps
  after_script:
    - stack hpc report .

hlint:
  script:
    - apt-get update -yqq
    - apt-get install -y --no-install-recommends libtinfo5
    - curl -sL https://raw.github.com/ndmitchell/hlint/master/misc/travis.sh | sh -s .
